/**
 * @packageDocumentation
 * @module api.functional.orders
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import type { TryCatch, IFailure } from "./../../interface/common/exception.interface";
import type { IOrder } from "./../../interface/order/order.interface";
import type { IOrderWithPayment, IOrderWithoutPayment } from "./../../interface/order/order-payment.interface";

/**
 * @summary 단건 주문 조회 API
 * @tag orders
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param order_id 주문 번호
 * @returns 주문 정보
 * 
 * @controller OrdersController.findOne()
 * @path GET /orders/:order_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function findOne
    (
        connection: IConnection,
        order_id: string
    ): Promise<findOne.Output>
{
    return Fetcher.fetch
    (
        connection,
        findOne.ENCRYPTED,
        findOne.METHOD,
        findOne.path(order_id)
    );
}
export namespace findOne
{
    export type Output = TryCatch<IOrder, IFailure.Business.Invalid | IFailure.Business.NotFound>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/orders/:order_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(order_id: string): string
    {
        return `/orders/${encodeURIComponent(order_id)}`;
    }
}

/**
 * PortOne에서 처리 후, 결제 상태를 확정하는 API
 * 
 * @summary 결제 완료 처리 API
 * @tag orders
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param order_id 주문 번호
 * @param body 주문 번호와 결제 서비스 고유 번호
 * @returns 주문 상세 정보
 * 
 * @controller OrdersController.complete()
 * @path POST /orders/:order_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function complete
    (
        connection: IConnection,
        order_id: string,
        body: IOrderWithPayment.ICreate
    ): Promise<complete.Output>
{
    return Fetcher.fetch
    (
        connection,
        complete.ENCRYPTED,
        complete.METHOD,
        complete.path(order_id),
        body,
        complete.stringify
    );
}
export namespace complete
{
    export type Input = IOrderWithPayment.ICreate;
    export type Output = TryCatch<IOrderWithPayment, IFailure.Business.Invalid | IFailure.Business.NotFound>;

    export const METHOD = "POST" as const;
    export const PATH: string = "/orders/:order_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(order_id: string): string
    {
        return `/orders/${encodeURIComponent(order_id)}`;
    }
    export const stringify = (input: Input) => typia.assertStringify(input);
}

/**
 * @summary 주문 생성 API
 * @tag orders
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param body 배송정보와 주문 상품 목록을 포함한다.
 * @returns 생성된 주문 정보
 * 
 * @controller OrdersController.create()
 * @path POST /orders
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function create
    (
        connection: IConnection,
        body: IOrder.CreateOrderBody
    ): Promise<create.Output>
{
    return Fetcher.fetch
    (
        connection,
        create.ENCRYPTED,
        create.METHOD,
        create.path(),
        body,
        create.stringify
    );
}
export namespace create
{
    export type Input = IOrder.CreateOrderBody;
    export type Output = TryCatch<IOrderWithoutPayment, IFailure.Business.Invalid>;

    export const METHOD = "POST" as const;
    export const PATH: string = "/orders";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/orders`;
    }
    export const stringify = (input: Input) => typia.assertStringify(input);
}