/**
 * @packageDocumentation
 * @module api.functional.token.refresh
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { TryCatch } from "./../../../interface/common/function.interface";

/**
 * Authorization header로 refresh_token을 전달헤야 합니다.
 * 
 * @summary 인증 토큰 재발행 API
 * @tag authentication
 * @returns 재발행된 access_token을 응답합니다.
 * @throw 4006 사용자를 찾을 수 없습니다.
 * @throw 4007 잘못된 토큰입니다.
 * 
 * @controller AuthController.refreshToken()
 * @path GET /token/refresh
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function refreshToken
    (
        connection: IConnection
    ): Promise<refreshToken.Output>
{
    return Fetcher.fetch
    (
        connection,
        refreshToken.ENCRYPTED,
        refreshToken.METHOD,
        refreshToken.path()
    );
}
export namespace refreshToken
{
    export type Output = TryCatch<string, { readonly code: "4006"; readonly data: "사용자를 찾을 수 없습니다."; } | { readonly code: "4007"; readonly data: "잘못된 토큰입니다."; }>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/token/refresh";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/token/refresh`;
    }
}