name: Test Coverage Comment
on:
  pull_request:
    branches: [ main ]
    
env:
  PORT: 4000
  ACCESS_TOKEN_PRIVATE_KEY: ${{ vars.ACCESS_TOKEN_PRIVATE_KEY }}
  ACCESS_TOKEN_PUBLIC_KEY: ${{ vars.ACCESS_TOKEN_PUBLIC_KEY }}
  REFRESH_TOKEN_PRIVATE_KEY: ${{ vars.ACCESS_TOKEN_PRIVATE_KEY }}
  REFRESH_TOKEN_PUBLIC_KEY: ${{ vars.ACCESS_TOKEN_PUBLIC_KEY }}
  DATABASE_URL: mysql://test:test@localhost:3306/test

jobs:
  coverage_comment:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
         - 3306:3306
        options:
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_USER: test
          MYSQL_ROOT_PASSWORD: root
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: test

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Setup database schema
        run: npm run db:deploy

      - name: Test 🧪
        run: npm run test:cov -- --coverageReporters json-summary

      - name: Comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          titie: Test Coverage Report
          badge-title: coverage
